version: 2
jobs:
  build:
    docker:
      - image: php:7.2-cli
        environment:
          GOSS_FILES_STRATEGY: cp
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e8:99:46:24:13:bd:5a:46:6e:f8:dd:d1:31:22:ca:2c"
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: |
            curl -L -o /tmp/docker-17.03.0-ce.tgz https://get.docker.com/builds/Linux/x86_64/docker-17.03.0-ce.tgz \
            && tar -xz -C /tmp -f /tmp/docker-17.03.0-ce.tgz \
            && mv /tmp/docker/* /usr/bin
      - run:
          name: Install goss
          command: curl -fsSL https://goss.rocks/install | sh
      - run:
          name: Build container.
          command: docker build -t 300788/ci-builder:latest .
      - run:
          name: Start container
          command: dgoss run -i 300788/ci-builder:latest
      - run:
          name: Build on Dockerhub
          command: |
            curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST "https://registry.hub.docker.com/u/300788/ci-builder/trigger/$DOCKERHUB_TOKEN/"